services:
  traefik:
    image: "traefik:v3.3"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      # Insert your email here
      - "--certificatesresolvers.myresolver.acme.email=example@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
    volumes:
      - "/data/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  grafana:
    build:
      context: grafana
      dockerfile: Dockerfile
    container_name: grafana
    volumes:
      - /data/grafana/grafana:/data/grafana
      - /data/grafana/prometheus:/data/prometheus
      - /data/grafana/loki:/loki
    environment:
      GF_PATHS_DATA: /data/grafana
    restart: always
    ports:
      - "127.0.0.1:4317:4317"
      - "127.0.0.1:3000:3000"
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/4317"
      interval: 30s
      timeout: 15s
      retries: 5
    labels:
      - "traefik.enable=true"
      # Insert your domain here
      - "traefik.http.routers.grafana.rule=Host(`monitoring.indexer.skyfeedlol.lol`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
      - "traefik.http.routers.grafana.middlewares=auth"
      # Generate a new password with `htpasswd -nB -C4 grafana`
      - "traefik.http.middlewares.auth.basicauth.users=grafana:$$2y$$04$$qxpOMWJdp4vMc2Z1u4afaeykArMJw7Y2cz.JeNKTVx/TfPu31TvQK"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
  db:
    image: postgres
    container_name: db
    restart: always
    user: root
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: user-name
      POSTGRES_PASSWORD: strong-password
    volumes:
      - /data/postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    user: root
    ports:
      - "127.0.0.1:8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - /data/pgadmin:/var/lib/pgadmin
    labels:
      - "traefik.enable=true"
      # Insert your domain here
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.indexer.skyfeedlol.lol`)"
      - "traefik.http.routers.pgadmin.entrypoints=websecure"
      - "traefik.http.routers.pgadmin.tls.certresolver=myresolver"
      - "traefik.http.routers.pgadmin.middlewares=auth"
      # Generate a new password with `htpasswd -nB -C4 pgadmin`
      - "traefik.http.middlewares.auth.basicauth.users=grafana:$$2y$$04$$qxpOMWJdp4vMc2Z1u4afaeykArMJw7Y2cz.JeNKTVx/TfPu31TvQK"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
  indexer:
    depends_on:
      db:
        condition: service_started
      grafana:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    container_name: indexer
    command:
      - --db=postgres://user-name:strong-password@db/user-name
      # Insert additional flags here
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://grafana:4317"
    restart: always
